Revert "Bump Microsoft.NETCore.UniversalWindowsPlatform"
This reverts commit 19389e33078b5af409b0d7bfbb23be7ef1cd4030.

Nice, this automatic update caused regression:

```
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(5,15): Error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(6,15): Error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(7,15): Error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(112,33): Error CS0246: The type or namespace name 'MidiInPort' could not be found (are you missing a using directive or an assembly reference?)
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(112,50): Error CS0246: The type or namespace name 'MidiMessageReceivedEventArgs' could not be found (are you missing a using directive or an assembly reference?)
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(84,10): Error CS0246: The type or namespace name 'DeviceInformation' could not be found (are you missing a using directive or an assembly reference?)
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(96,26): Error CS0246: The type or namespace name 'MidiInPort' could not be found (are you missing a using directive or an assembly reference?)
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(104,3): Error CS0246: The type or namespace name 'MidiInPort' could not be found (are you missing a using directive or an assembly reference?)
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(188,15): Error CS0246: The type or namespace name 'IMidiMessage' could not be found (are you missing a using directive or an assembly reference?)
Commons.Music.Midi.UwpShared\UwpMidiAccess.cs(135,27): Error CS0246: The type or namespace name 'IMidiOutPort' could not be found (are you missing a using directive or an assembly reference?)
```